# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HA9J9DwxwebIs8UAZWaKbujSR7bfJhPe
"""

# Deklarasi array kosong
data = []

# Inisilisasi array dengan elemen
angka = [1, 20, 30, 40, 50]

# Menampilkan isi array
print("Isi array angka:", angka)

"""Latihan 1"""

NPM = [2420506025, 2420506026, 2420506027, 2420506028, 2420506029]
print("Isi array NPM:", NPM)

# Mengkases elemen Array
print("Elemen pertama:", angka[0]) # Elemenpertama
print("Elemen terakhir:", angka[-1]) # Elemen terakhir

# Menambah elemen menggunakan append()
angka.append(60)
print("Array setelah penambahan elemen:", angka)

# Menambah elemen menggunakan insert()
angka.insert(2, 25) # Mnyisipkan 25 di indeks ke-2
print("Array setelah penambahan elemen dengan insert:", angka)

# Menghapus elemen menggunakan remove()
angka.remove(25) # Menghapus nilai 25
print("Array setelah menghapus elemen 25:", angka)

# Menghapus elemen menggunakan pop()
angka.pop(2) # Menghapus elemen pada indeks ke-2
print("Array setelah menghapus elemen pada indeks ke-2:", angka)

# Mengubah elemen pada indeks 0
angka[0] = 100
print("Angka setelah elemen pertama:", angka)

"""Latihan 2"""

angka.append(25)
angka.pop(0)
print("Array setelah penambahan elemen dan penghapusan elemen pertama:", angka)

angka = [10, 20, 30, 40]

for nilai in angka:
  print("Nilai:", nilai)

"""Latihan 3"""

fakultas = ["Teknik", "Ekonomi", "Ilmu Sosiologi dan Ilmu Politik", "Pertanian", "Keguruan dan Ilmu Pendidikan"]
for i in fakultas:
  print("Fakultas", i)

angka = [10, 20, 30, 40]

print("Jumlah total:", sum(angka))
print("Nilai maksimum:", max(angka))
print("Nilai minimum:", min(angka))

"""Latihan 4"""

paket_makan = [10000, 12000, 15000, 18000]

print("Paket makan yang tersedia:")
for i in paket_makan:
  print("Rp.", i)
print("Jumlah total: Rp.", sum(paket_makan))

# Deklarasi array 2D
matriks = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

# Menampilkam isi array 2D
print("Isi array 2D:")
for baris in matriks:
  print(baris)

"""Latihan 5"""

matrix = [
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
]

print("Isi array 2D matrix:")
for baris in matrix:
  print(baris)

# Mengakses elemen pada baris ke-1, kolom ke-2 (indkes [0][1])
print("Elemen pada baris ke-1, kolom ke-2:", matrix[0][1])

# Mengkases elemen terakhir (baris ke-3, kolom ke-3)
print("Elemen terakhir:", matrix[-1][-1])

"""Latihan 6"""

print("Elemen pada baris ke-2, kolom ke-4 dari array matrix:", matrix[1][3])

# Menambahkan baris baru
matriks.append([10, 11, 12])
print("Array setelah menambah baris baru:")
for baris in matriks:
  print(baris)

# Menambah elemen pada baris ke-2
matriks[1].append(99)
print("Array setelahmenambahkan elemen di baris ke-2:")
for baris in matriks:
  print(baris)

"""Latihan 7"""

matrix.append([9, 7, 20, 4])
print("Matrix setelah ditambahkan elemen baru:")
for baris in matrix:
  print(baris)

# Menghapus elemen tertentu dari baris ke-1
matriks[0].remove(2)
print("Array setelah menghapus elemen 2 dari baris pertama:")
for baris in matriks:
  print(baris)

# Menghapus elemen pada indeks tertentu dari baris ke-2
matriks[1].pop(1)
print("Array setetlah menghapus elemen indeks ke-1 dari baris ke-2:")
for baris in matriks:
  print(baris)

"""Latihan 8"""

matrix[-1].pop(2)
print("Array setelah menghapus elemen ke-3 dari baris terakhir:")
for baris in matrix:
  print(baris)

# Mengubah elemen pada baris ke-3, kolom ke-2
matriks[2][1] = 88
print("Array setelah mengubah elemen baris ke-3 kolom ke-2:")
for baris in matriks:
  print(baris)

"""Latihan 9"""

matrix[-1][-1] = 14
print("Array matrix setelah mengubah elemen terakhir dari baris terakhir:")
for baris in matrix:
  print(baris)

belanja = ["Beras", "Gula", "Minyak"]
print("Daftar belanja:", belanja)
belanja.append("Teh")
belanja.remove("Gula")
print("Daftar belanja terbaru:", belanja)

"""Latihan 10"""

tuku = ["Ram", "Martabat", "Rasa Sabar"]
print("Daftar belanja tahun 2025:", tuku)
tuku.append("Kuat")
tuku.remove("Ram")
print("daftar belanja 2025 terbaru:", tuku)

size = 10
treasure_map = ["_" for _ in range(size)]

print(f"Selamat datang di Treasure Hunt! Peta memiliki {size} lokasi (0 hingga {size-1}).")
treasure_index = int(input("Silahkan pilih lokasi (0 hingga {size-1}):"))
while treasure_index < 0 or treasure_index >= size:
  print("Lokasi tidak valid. Masukkan angka dalam rentang yang benar.")
  treasure_index = int(input(f" Masukkan lokasi harta karun (0-{size-1}):"))

treasure_map[treasure_index] = "X"

def play_treasure_hunt():
  print("\nHarta karun telah disembunyikan! Sekarang giliran pemain menebak.")
  print("Cobalah untuk menemukan harta karun dengan menebak indeks yang benar.")

  # Loop permainan
  while True:
    print("n\Peta saat ini: ", ["_" for _ in range(size)])
    try:
      guess = int(input(f"Masukkan indeks tebakkanmu (0-{size-1}):"))
    except ValueError:
      print("Masukkan angka yang valid!")
      continue
    if guess < 0 or guess >= size:
      print("Indeks tidak valid, pilih diantara 0 hingga", size-1)
      continue
    if treasure_map[guess] == "X":
      print("🎉 Selamat! Kamu menemukan harta karun dilokasi:", guess)
      break
    else:
      print("❌ Tidak ada harta di lokasi ini. Coba lagi!")

  print("Terima kasih sudah bermain!")

play_treasure_hunt()

import random

def ukuran_peta(promt):
      while True:
        try:
            nilai = input(promt)
            if nilai == "":
                print("Input tidak boleh kosong.")
                continue
            elif nilai == "0":
                print("Input tidak boleh nol.")
                continue
            elif not nilai.isdigit():
                print("Invalid input. Input harus berupa angka")
                continue
            else:
                return int(nilai)
        except ValueError:
            print("Invalid input. Input harus berupa angka.")

treasure_map = []

print(f"Selamat datang di Treasue Hunt! Kamu dapat menenmukan harta karun disini, tebaklah lokasinya!")
size = ukuran_peta("Masukkan Ukuran peta, semakin besar ukurannya semakin asik!:")
treasure_map = ["_" for _ in range(size)]
treasure_index = random.randint(0,size-1)
while treasure_index <0 or treasure_index >= size:
  print ("Lokasi tidak valid. Masukkan angka dalam rentang yang benar.")
  treasure_index = int (input(f"Masukkan lokasi harta karun (0-{size-1}):"))

treasure_map[treasure_index] = "X"

def play_treasure_hunt():
  print ("\nHarta karun telah disembunyikan! Sekarang giliran pemain menebak.")
  print("Cobalah unruk menemukan harta karun dengan menebak index yang benar.")

  while True:
    print("\nPeta saat ini: ", ["_" for _ in range(size)])
    try:
      guess = int(input(f"Masukkan index tebakanmu (0-{size-1}):\n"))
      if guess <0 or guess >= size:
        print ("Indeks tidak valid, pilih antara 0 hingga ",size-1)
        continue
      if treasure_map[guess] == "X":
        print ("Selamat!🎉🎉 Kamu menemukan harta karun di lokasi:",guess)
        break
      else:
        print("❌❌ Tidak ada harta karun di lokasi ini. Coba lagi!")
    except ValueError:
        print ("Masukkan angka yang valid:")
        continue

  print("Terimakasih sudah bermain!")

play_treasure_hunt()

1